# action.yml
name: "huacnlee.autocorrect"
description: "Use autocorrect to check."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for autocorrect"
    required: false
    default: "./ --lint"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
