# action.yml
name: "AutoCorrect"
description: "Use autocorrect to check."
inputs:
  args: # id of input
    description: "args for autocorrect"
    required: false
    default: "./ --lint"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
